// import { test, expect } from '@playwright/test';
// import path from 'path';

// test('test', async ({ page }) => {
//   await page.goto('http://localhost:7891/registration');
//   await page.getByRole('textbox', { name: 'Name: *', exact: true }).click();
//   await page.getByRole('textbox', { name: 'Name: *', exact: true }).fill('ssi');
//   await page.getByText('Enter your typeRemove item').click();
//   await page.getByText('Local Investor').click();
//   await page.getByText('Select your economic zoneRemove item').click();
//   await page.getByRole('option', { name: 'Government Owned Economic Zone' }).click();
//   await page.getByText('Select zone nameSelect zone').click();
//   await page.getByText('Shrihatta Economic Zone').click();
//   await page.getByRole('checkbox', { name: 'Does have Land Lease Agreement' }).check();
//   await page.getByText('Select your nationalityRemove').click();
//   await page.getByRole('option', { name: 'Bangladeshi' }).click();
//   await page.getByRole('radio', { name: 'National ID' }).check();
//   await page.getByRole('textbox', { name: 'National ID: *' }).click();
//   await page.getByRole('textbox', { name: 'National ID: *' }).fill('00000007757876');
//   await page.getByRole('textbox', { name: 'Select your date of birth' }).click();
//   await page.getByLabel('June 3,').click();
//   await page.getByRole('textbox', { name: 'Designation: *' }).click();
//   await page.getByRole('textbox', { name: 'Designation: *' }).fill('owner');
//   await page.getByText('Select your countryRemove item').click();
//   await page.getByRole('option', { name: 'Bangladesh' }).click();
//   await page.getByText('Select your divisionRemove').click();
//   await page.getByRole('option', { name: 'Rajshahi' }).click();
//   await page.getByText('Select your districtRemove').click();
//   await page.getByRole('option', { name: 'Pabna' }).click();
//   await page.getByRole('textbox', { name: 'Address Line 1: *' }).click();
//   await page.getByRole('textbox', { name: 'Address Line 1: *' }).fill('3ghjkjeyjh');
//   await page.getByText('Select countryRemove item').click();
//   await page.getByRole('option', { name: '(AFG)' }).click();
//   await page.getByRole('textbox', { name: 'Enter mobile number' }).click();
//   await page.getByRole('textbox', { name: 'Enter mobile number' }).fill('0987654');
//   await page.getByText('Select a company typeRemove').click();
//   await page.getByRole('option', { name: 'Existing company' }).click();
//   await page.getByRole('textbox', { name: 'Company Name: *' }).click();
//   await page.getByRole('textbox', { name: 'Company Name: *' }).fill('shanto ltd');
//   await page.getByText('Select a countryRemove item').click();
//   await page.getByRole('option', { name: 'Bangladesh' }).click();
//   const filePath = '/home/shafin/Documents/practice/Automation/files/demo.pdf';
//   const imagePath = '/home/shafin/Documents/practice/Automation/files/demo.png';
//   await page.getByRole('link', { name: 'browse Browse to attach file for Copy of MOA:' }).click();
//   const uploadFile = page.locator('input[type="file"]'); 
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file for Land lease agreement:. Allowed file types:' }).click();
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file for Copy of AoA:. Allowed file types: application/' }).click();
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file for Details of Signatory (Form XII):. Allowed file' }).click();
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file for Authorization Letter' }).click();
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file for Scan of NID/Passport:. Allowed file types:' }).click();
//   await uploadFile.setInputFiles(filePath);
//   await page.getByRole('link', { name: 'browse Browse to attach file' }).click();
//   await uploadFile.setInputFiles(imagePath);
//   await page.getByRole('textbox', { name: 'User Email: *' }).click();
//   await page.getByRole('textbox', { name: 'User Email: *' }).fill('t@ay.com');
//   await page.getByRole('textbox', { name: 'Password: *', exact: true }).click();
//   await page.getByRole('textbox', { name: 'Password: *', exact: true }).fill('hphphp');
//   await page.getByRole('textbox', { name: 'Confirm Password: *' }).click();
//   await page.getByRole('textbox', { name: 'Confirm Password: *' }).fill('hphphp');
//   await page.getByRole('checkbox', { name: 'I have read and agree to the' }).check();  
//   await page.getByRole('button', { name: 'SUBMIT' }).click();
// });